name: CI/CD Pipeline

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]

env:
    REGISTRY: ghcr.io/b-nockk # ← changed
    SHA: ${{ github.sha }}

jobs:
    lint:
        uses: ./.github/workflows/_lint.yml

    test:
        needs: lint
        uses: ./.github/workflows/_test.yml

    build-and-scan:
        needs: test
        uses: ./.github/workflows/_build-and-scan.yml
        permissions:
            security-events: write
            packages: write
        with:
            registry: "ghcr.io/b-nockk"
            sha: ${{ github.sha }}

    integration:
        needs: build-and-scan
        uses: ./.github/workflows/_integration.yml

    deploy:
        needs: integration
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: ./.github/workflows/_deploy.yml
        secrets: inherit
        with:
            sha: ${{ github.sha }}
            registry: "ghcr.io/b-nockk"
